Update closure-ci.yml

diff --git a/.github/workflows/closure-ci.yml b/.github/workflows/closure-ci.yml
--- a/.github/workflows/closure-ci.yml
+++ b/.github/workflows/closure-ci.yml
@@ -76,12 +76,7 @@ jobs:
           - name: Set up Azure CLI
             uses: azure/login@v1
             with:
-              creds: |
-                subscription-id:${{ secrets.AZURE_SUBSCRIPTION_ID }}
-                tenant-id:${{ secrets.AZURE_TENANT_ID }}
-                client-id:${{ secrets.AZURE_CLIENT_ID }}
-                client-secret:${{ secrets.AZURE_CLIENT_SECRET }}
-  
+              creds: ${{ secrets.AZURE_CREDENTIALS }}
           - name: Set up kubectl
             uses: azure/setup-kubectl@v1
       
@@ -103,12 +98,8 @@ jobs:
                     - name: Set up Azure CLI
                       uses: azure/login@v1
                       with:
-                        creds: |
-                            ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-                            ${{ secrets.AZURE_TENANT_ID }}
-                            ${{ secrets.AZURE_CLIENT_ID }}
-                            ${{ secrets.AZURE_CLIENT_SECRET }}
-            
+                        creds: ${{ secrets.AZURE_CREDENTIALS }}
+                            
                     - name: Set up kubectl
                       uses: azure/setup-kubectl@v1
                 
@@ -118,6 +109,12 @@ jobs:
                     - name: Apply Kubernetes manifests
                       run: |
                         kubectl apply -f newsfeed.yaml
+                        if [ $? -eq 0 ]; then
+                        echo "Terraform apply succeeded."
+                        else
+                        echo "Terraform apply failed. Clean up"
+                        terraform destroy -auto-approve
+                        fi
 
   deploy_frontend:
       needs: deploy_newsfeed
@@ -130,11 +127,7 @@ jobs:
                 - name: Set up Azure CLI
                   uses: azure/login@v1
                   with:
-                      creds: |
-                            ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-                            ${{ secrets.AZURE_TENANT_ID }}
-                            ${{ secrets.AZURE_CLIENT_ID }}
-                            ${{ secrets.AZURE_CLIENT_SECRET }}
+                      creds: ${{ secrets.AZURE_CREDENTIALS }}
                                 
                 - name: Set up kubectl
                   uses: azure/setup-kubectl@v1
@@ -150,4 +143,5 @@ jobs:
                 
                 - name: Apply Kubernetes manifests
                   run: |
+                        kubectl apply -f secrets.yaml
                         kubectl apply -f frontend.yaml
