seprated pipelines

diff --git a/.github/workflows/create_azure_infra.yml b/.github/workflows/create_azure_infra.yml
--- a/.github/workflows/create_azure_infra.yml
+++ b/.github/workflows/create_azure_infra.yml
@@ -39,3 +39,9 @@ jobs:
               run: |
                 cd terraform
                 terraform apply -auto-approve -input=false
+                if [ $? -eq 0 ]; then
+                echo "Terraform apply succeeded."
+                else
+                echo "Terraform apply failed. Clean up"
+                terraform destroy -auto-approve
+                fi
